questions_data_path: "data/data_31_10_2024/translated"
rag_generated_questions_number: 10
rag_great_grade_threshold: 0.8
rag_good_grade_threshold: 0.5
rag_topics_list: [
  "Линейные модели",
  "Метрические методы",
  "Решающие деревья",
  "Ансамбли в машинном обучении",
  "Градиентный бустинг",
  "Метрики классификации и регрессии",
  "Кросс-валидация",
  "Подбор гиперпараметров",
  "Вероятностный подход в ML",
  "Экспоненциальный класс распределений и принцип максимальной энтропии",
  "Обобщённые линейные модели",
  "Как оценивать вероятности",
  "Генеративный подход к классификации",
  "Байесовский подход к оцениванию",
  "Модели с латентными переменными",
  "Нейронные сети",
  "Первое знакомство с полносвязными нейросетями",
  "Метод обратного распространения ошибки",
  "Тонкости обучения"
]
